# Generated by Django 2.2 on 2020-07-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='worker',
            new_name='user_posted_job',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='accept_job',
            new_name='user_with_job',
        ),
    ]
