# Generated by Django 2.2 on 2020-07-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200723_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_posted_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_job', to='log_reg_app.User'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user_with_job',
            field=models.ManyToManyField(related_name='with_job', to='log_reg_app.User'),
        ),
    ]
